spring:
  application:
    name: nasiya-savdo
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost:5432}/nasiya-savdo
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update # Apply missing Flyway scripts to DB, and validate if JPA and DB model match during startup
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 100MB  # Set the desired maximum file size
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

auth0:
  clientSecret: zSAZad3TDWqyKHqtfp83ksK8kY99KhU8
  accessTokenExpirationMinutes: 120  # 2 hours
  refreshTokenExpirationDays: 1  # 1 day

application:
  file:
    dir: /nasiya-savdo/file/
    allowed-extensions: png,jpeg,jpg,heic